### PR TITLE
Add ability to have decimal places in pension contributions #20

### LINKED ISSUE #20: Add ability to have decimal places in pension contributions
I currently contribute to my pension an amount of x.5%

Currently the form only allows integer pension contributions.

I would be happy to raise a PR if it would be helpful.

### PR DESCRIPTION
**Pull request by Donbasilpeter**
added decimal point to the pension enrolement field.
closes #20 

image

### CODE REVIEW

**Comment by Ross-mc** [comment]
There's a step attribute on the input that should also be updated.

A value of 0.01 seems appropriate for the step.

**Comment by wozniakpawel** [comment]
@Ross-mc I actually think it is best to keep it at 1, that is only used for mouse input and I think you'd not want to click 830 times to set it to 8.3% 😂

**Comment by wozniakpawel** [comment]
@Donbasilpeter 
This doesn't actually seem to work on my system, the input disappears as soon as I press a dot. Can you double check the preview and see if it works for you?

**Comment by Ross-mc** [comment]
> @Donbasilpeter This doesn't actually seem to work on my system, the input disappears as soon as I press a dot. Can you double check the preview and see if it works for you?

The preview worked for me and also running locally it works. I've tried it on Firefox and Chrome.

image

**Comment by wozniakpawel** [comment]
Okay, I just checked and it works on Chrome. Before I merge it, could you work out how to fix it on Safari? It's broken on both macOS and iOS (iPhone). Also maybe prevent user from inserting numbers smaller than 2 decimal places

**Review by wozniakpawel — CHANGES_REQUESTED** [review]
Please do the following:
- change the auto enrolment step size to 0.1
- see if you can fix issues on Safari (does not allow decimal places for some reason)

**Comment by Ross-mc** [comment]
> Please do the following:
> 
> * change the auto enrolment step size to 0.1
> * see if you can fix issues on Safari (does not allow decimal places for some reason)

Step is required on Safari in order to allow the user to enter decimal places. On Chrome/Firefox decimal places can be entered regardless of step.

So adding the step should fix the Safari issue

**Comment by wozniakpawel** [comment]
That was my suspicion but I couldn’t get it to work even with a step size (local build). This needs to be worked out & resolved before a merge.

**Comment by wozniakpawel** [comment]
Having no responses, so I will close the PR. Already fixed in #43

**Pull request closed without merging**
