### PR TITLE
Rounded student loan repayments to nearest pound

### LINKED ISSUE #24: Round Student Loan Repayments down to the nearest pound

### PR DESCRIPTION
**Pull request by sjdex**
Closes #24

### CODE REVIEW

**Review by wozniakpawel — CHANGES_REQUESTED** [review]
Hi. I think it makes sense to move this inside the calculateStudentLoanRepayments function instead.

**Comment by sjdex** [comment]
Oh, so basically we want the floor value of the given result.

**Comment by sjdex** [comment]
Math.floor() will do the trick. I hope thats what we want here.

**Review by wozniakpawel — APPROVED** [review]
LGTM

**Pull request merged**
